<template>
    <div>
        TERMS OF USE superjs.org
<br><br>
Welcome to superjs.org a website owned and operated by Jekyll Technologies LLC.
<br><br>
ADULT CONTENT NOTICE. THIS WEBSITE CONTAINS SEXUALLY EXPLICIT ADULT CONTENT. YOU MUST BE 18 YEARS OF AGE OR OLDER TO USE THIS SITE. By using this Site you represent that the jurisdiction from which you access the website does not prohibit the receiving or viewing of sexually explicit content.
<br><br>
GENERAL DISCLAIMER. superjs.org SPECIFICALLY DISCLAIMS LIABILITY FOR CONTENT POSTED BY MEMBERS AND USERS, AS WELL AS CONTENT LINKED-TO OR PROVIDED BY THIRD PARTIES. superjs.org HEREBY DISCLAIMS ANY AND ALL WARRANTIES, EXPRESS AND IMPLIED, REGARDING THE TRUTH, ACCURACY AND RELIABILITY, OR USABILITY OF THE INFORMATION OR PRODUCTS ON THIS WEBSITE.
<br><br>
YOU, THE USER, REPRESENT AND AGREE THAT IN USING THIS SITE YOU WILL COMPLY WITH ALL RELEVANT LEGAL OBLIGATIONS IN YOUR JURISDICTION, TO THE EXTENT THEY MAY APPLY TO YOU.
<br><br>
BINDING EFFECT. This is a binding agreement. By using the website located at superjs.org (the "Site") or any services provided in connection with the Site (the "Service"), you agree to abide by these Terms of Use, as they may be amended by superjs.org ("Company") from time to time in its sole discretion. Superjs.org will post a notice on the Site any time these Terms of Use have been changed or otherwise updated. Superjs.org will also send registered Users an email notifying them of any changes to these Terms, or otherwise advise registered Users via their registration profile.
<br><br>
It is your responsibility to review these Terms of Use periodically, and if at any time you find these Terms of Use unacceptable, you must immediately leave the Site and cease all use of the Service and the Site.
<br><br>
YOU AGREE THAT BY USING THE SERVICE YOU REPRESENT THAT YOU ARE AT LEAST 18 YEARS OF AGE, and are fully competent and able to enter into and abide by the terms, obligations, and warranties of these Terms, and will to comply with these Terms. If you are under 18 or the applicable age of majority in your jurisdiction, you are not permitted to register with superjs.org, or to utilize any of its sexually explicit features, or to purchase any goods or services.
<br><br>
REGISTRATION. You are not required to register to view the superjs.org Site; however certain features are limited or unavailable to unregistered users. To fully utilize the services offered by superjs.org, you will need to register with the Site. When you open an account to use or access the Site or Service, you must complete the registration process by providing the complete and accurate information requested on the registration form. (You are not required to provide information where it is indicated as optional, however you are recommended to do so in order to enhance your browsing experience). You will also be asked to provide a username and password. You are entirely responsible for maintaining the confidentiality of your password. You may not use the account, username, or password of someone else at any time.
<br><br>
You agree to notify superjs.org immediately of any unauthorized use of your account, username, or password. Superjs.org shall not be liable for any loss that you incur as a result of someone else using your password, either with or without your knowledge. You may be held liable for any losses incurred by superjs.org, its affiliates, officers, directors, employees, consultants, agents, and representatives due to someone else's use of your account or password.
<br><br>
SOCIAL MEDIA INTEGRATION: In addition to its own social media services, superjs.org may integrate with various social media sites such as Facebook, Twitter, etc. If you utilize such integration, you agree that you are bound by and will abide by the Terms of Use of any integrated sites in addition to these Terms.
<br><br>
FEES; PAYMENT AND RENEWAL. Some products and services available through or in connection with this Site require that you purchase a subscription or otherwise pay a fee. These may include some social media features, videos, images, or products and services provided by superjs.org, or by third-party providers. You hereby authorize the Company and its merchant provider to charge your credit card, PayPal account or other means of payment made available to you, in advance, for all applicable fees incurred by you or on your behalf in connection with the product or service you have chosen to use. You are solely responsible for all charges, fees, duties, taxes, and assessments arising out of any use of your account by you or anyone else using your account. The Company reserves the right to change the amount of, or basis for determining, any fees or charges for services it provides, and to institute new fees, charges, or terms effective upon prior notice to customers. The Company reserves the right to terminate any account at any time for any reason.
<br><br>
Your right to use the Service is subject to any expenditure limits established by the Company or by your credit card issuer or other means of payment that may be made available to you. If payment cannot be charged to your credit card, or collected by other available means on the Site, or your charge is returned for any reason, including chargeback, Company reserves the right to either suspend or terminate your access and account, thereby terminating this Agreement and all obligations of Company hereunder.
<br><br>
If you have reason to believe that your account is no longer secure (for example, in the event of a loss, theft or unauthorized disclosure or use of your ID, password, or any credit, debit, or charge card number stored, if any), notify the Company of the problem to avoid possible liability for any unauthorized charges to your account.
<br><br>
It is your responsibility to notify the Company if your credit card has changed or has expired and to make appropriate changes or your service may be disconnected or interrupted.
<br><br>
PAID CONTENT. In addition to fees relating to subscriptions or purchases, we may charge a fee to post Content in some areas of the Service. This Content may include banner and text advertisements, sponsorships, event listings, etc. The fee may be an access fee permitting Content to be posted in a designated area, and/or paid advertising. Each party posting Content to the Service is responsible for said Content and compliance with this Terms of Use and any other applicable agreement between the parties. All fees paid will be non-refundable in the event that Content is removed from the Service for violating these Terms.
<br><br>
SPECIALS, PROMOTIONS, SWEEPSTAKES. Please read the official rules that accompany any gift opportunity, special offer, coupon, discount, contest and sweepstakes that we may offer or conduct. Rules for any of the above are incorporated into this Agreement by this reference.
<br><br>
PRIVACY POLICY. superjs.org respects your privacy and permits you to control the treatment of your personal information. A complete statement of superjs.org's current privacy policy can be found by clicking here. Superjs.org's privacy policy is expressly incorporated into this Agreement by this reference.
<br><br>
INDEPENDENT CONTRACTORS. All subscribers, users, affiliates, and other parties using the Site, including specifically those who contribute content commercial or noncommercial to the Site, are Independent Contractors. Neither Jekyll Technologies LLC nor parties providing content to the site, and their agents and employees, are partners, agents, representatives, joint ventures or employees of the other party.
<br><br>
USER CONTENT. You grant Company a license to use the materials you post to the Site or Service. By posting, downloading, displaying, performing, transmitting, or otherwise distributing information or other content ("User Content") to the Site or Service, you are granting Company, its affiliates, officers, directors, employees, consultants, agents, and representatives a license to use User Content in connection with the operation of the business of Company, its affiliates, officers, directors, employees, consultants, agents, and representatives, including without limitation, a right to copy, distribute, transmit, publicly display, publicly perform, reproduce, edit, translate, and reformat User Content. You will not be compensated for any User Content, unless you have entered into a separate agreement with Company for compensation.  You agree that Company may publish or otherwise disclose your username or other information you agree to disseminate, in connection with your User Content. By posting User Content on the Site or Service, you warrant and represent that you own the rights to the User Content or are otherwise authorized to post, distribute, display, perform, transmit, or otherwise distribute User Content.
<br><br>
COMPLIANCE WITH INTELLECTUAL PROPERTY LAWS. When accessing the Site or using the Service, you agree to obey the law and to respect the intellectual property rights of others. Your use of the Service and the Site is at all times governed by and subject to laws regarding copyright ownership and use of intellectual property. You agree not to upload, download, display, perform, transmit, or otherwise distribute any information or content (collectively, "Content") in violation of any third party's copyrights, trademarks, or other intellectual property or proprietary rights. You agree to abide by laws regarding copyright ownership and use of intellectual property, and you shall be solely responsible for any violations of any relevant laws and for any infringements of third party rights caused by any Content you provide or transmit, or that is provided or transmitted using your User ID. The burden of proving that any Content does not violate any laws or third party rights rests solely with you.
<br><br>
COPYRIGHT INFRINGEMENT. Superjs.org has in place certain legally mandated procedures regarding allegations of copyright infringement occurring on the Site or with the Service. Superjs.org has adopted a policy that provides for the immediate suspension and/or termination of any Site or Service user who is found to have infringed on the rights of Company or of a third party, or otherwise violated any intellectual property laws or regulations. Superjs.org's policy is to investigate any allegations of copyright infringement brought to its attention. If you have evidence, know, or have a good faith belief that your rights or the rights of a third party have been violated and you want Company to delete, edit, or disable the material in question, you must provide Company with all of the following information: (a) a physical or electronic signature of a person authorized to act on behalf of the owner of the exclusive right that is allegedly infringed; (b) identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works are covered by a single notification, a representative list of such works; (c) identification of the material that is claimed to be infringed or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit Company to locate the material; (d) information reasonably sufficient to permit Company to contact you, such as an address, telephone number, and if available, an electronic mail address at which you may be contacted; (e) a statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and (f) a statement that the information in the notification is accurate, and under penalty of perjury, that you are authorized to act on behalf of the owner of an exclusive right that is allegedly infringed. For this notification to be effective, you must provide it to Company's designated agent at:
<br><br>
superjs.org Copyright Dept.
Jekyll Technologies LLC
erichui329@gmail.com
<br><br>
INAPPROPRIATE CONTENT. You shall not make the following types of Content available. You agree not to upload, download, display, perform, transmit, or otherwise distribute any Content that:
<br><br>
(a) violates any of the terms of this Agreement, or any agreement with superjs.org or its partners, affiliates, or third-party data providers or other third-party providers as outlined herein; or<br><br>
(b) creates a false identity for the purpose of misleading others; or<br><br>
(c) is libelous, defamatory, obscene, abusive, harassing, threatening, hateful, or advocates violence; or<br><br>
(d) advocates or encourages conduct that could constitute a criminal offense, give rise to civil liability, or otherwise violate any applicable local, state, national, or foreign law or regulation; or<br><br>
(e) violates any law (including laws related to torts, contracts, patents, trademarks, trade secrets, copyrights, obscenity, pornography, or other rights) or encourage or provide instructions to another to do so; or<br><br>
(f) depicts any person under 18 years of age; or<br><br>
(g) you do not have written documentation regarding the content to support that all subjects of your uploads or posts are, in fact, over 18 years of age; or
(h) depicts child pornography, rape, snuff, torture, death, violence, or incest, racial slurs or hate speech; or<br><br>
(i) contains copyrighted materials, or materials protected by other intellectual property laws, that you do not own or for which you have not obtained all necessary written permissions and releases; or<br><br>
(j) includes surveys, contests, pyramid schemes, chain letters, junk mail, spam, or unsolicited messages; or<br><br>
(k) includes currency or stock quotes, online trading, investment offers or similar financial advice; or<br><br>
(l) contains viruses, Trojan horses, worms, or similar destructive, invasive, or illegal software.<br><br>

superjs.org reserves the right to terminate your receipt, transmission, or other distribution of any such material using the Service, and, if applicable, to delete any such material from its servers.<br><br>

superjs.org intends to cooperate fully with any law enforcement officials or agencies in the investigation of any violation of these Terms of Use or of any applicable laws. superjs.org reserves the right to prosecute to the fullest extent of the law criminal violations of the above-listed restrictions or other criminal violations of this Agreement.<br><br>

18 USC 2257 NOTICE<br><br>

RRFLI.net does not produce or participate in the production of any of the sexually explicit or erotic content found on this Site. Any records required by 18 USC 2257 are maintained by the parties who produced such content.<br><br>

In relation to video-sharing features by users or affiliate sites, superjs.org takes reasonable steps to verify compliance, but makes no representations about the accuracy of compliance by third parties. For assistance and/or information in determining the originating site or party of specific content, please contact superjs.org compliance at erichui329@gmail.com.<br><br>

superjs.org takes the steps to ensure compliance:<br><br>

It requires all users to be 18 years of age to upload adult content.<br><br>
Users 	who upload adult content must verify the content, represent that they are at least 18 years of age, and certify that they maintain records of the models/actors in the content and that they are over 18 years of age.<br><br>

superjs.org will allow content to be flagged as inappropriate. Should any content be flagged as illegal, unlawful, harassing, harmful, offensive or various other reasons, superjs.org shall reasonably investigate and remove any inappropriate material from the Site. Users are encouraged to flag inappropriate content.<br><br>

PROHIBITED USES. superjs.org imposes certain restrictions on your permissible use of the Site and the Service. You are prohibited from violating or attempting to violate any security features of the Site or Service, including, without limitation, (a) accessing content or data not intended for you, or logging onto a server or account that you are not authorized to access; (b) attempting to probe, scan, or test the vulnerability of the Service, the Site, or any associated system or network, or to breach security or authentication measures without proper authorization; (c) interfering or attempting to interfere with service to any user, host, or network, including, without limitation, by means of submitting a virus to the Site or Service, overloading, DDoS attacks, "flooding," "spamming," "mail bombing," etc.; (d) using the Site or Service to send unsolicited email, including, without limitation, promotions, or advertisements for products or services; (e) forging any TCP/IP packet header or any part of the header information in any email or in any posting using the Service; or (f) attempting to modify, reverse-engineer, decompile, disassemble, or otherwise reduce or attempt to reduce to a human-perceivable form any of the source code used by Company in providing the Site or Service. Any violation of system or network security may subject you to civil and/or criminal liability prosecution.<br><br>

ALLEGED VIOLATIONS. Superjs.org reserves the right to terminate your use of the Service and/or the Site. To ensure that Company provides a high quality experience for you and for other users of the Site and the Service, you agree that Company or its representatives may access your account and records on a case-by-case basis to investigate complaints or allegations of abuse, infringement of third party rights, or other unauthorized uses of the Site or the Service. Company does not intend to disclose the existence or occurrence of such an investigation unless required by law, but Company reserves the right to terminate your account or your access to the Site immediately, with or without notice to you, and without liability to you, if Company believes that you have violated any of the Terms of Use, furnished Company with false or misleading information, or interfered with use of the Site or the Service by others.<br><br>

INTERNATIONAL AND U.S. USE. Recognizing the global nature of the Internet, you agree to comply with all local rules regarding online conduct and acceptable Content and the legality of your use of the information provided. The Site is based in the State of California, USA. superjs.org makes no representation that any of the materials, products, or services to which you have been given access are available or appropriate for use in other locations. Your use of or access to the Site should not be construed as Company's purposefully availing itself of the benefits or privilege of doing business in any state or jurisdiction other than California.<br><br>

NO WARRANTIES. superjs.org HEREBY DISCLAIMS ALL WARRANTIES. COMPANY IS MAKING THE SITE AVAILABLE "AS IS" WITHOUT WARRANTY OF ANY KIND. YOU ASSUME THE RISK OF ANY AND ALL DAMAGE OR LOSS FROM USE OF, OR INABILITY TO USE, THE SITE OR THE SERVICE. TO THE MAXIMUM EXTENT PERMITTED BY LAW, COMPANY EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES, EXPRESS OR IMPLIED, REGARDING THE SITE, INCLUDING, BUT NOT LIMITED TO, ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NONINFRINGEMENT. COMPANY DOES NOT WARRANT THAT THE SITE OR THE SERVICE WILL MEET YOUR REQUIREMENTS OR THAT THE OPERATION OF THE SITE OR THE SERVICE WILL BE UNINTERRUPTED OR ERROR-FREE.<br><br>

LIMITED LIABILITY. Superjs.org'S LIABILITY TO YOU IS LIMITED. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL COMPANY BE LIABLE FOR DAMAGES OF ANY KIND (INCLUDING, BUT NOT LIMITED TO, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, LOST PROFITS, OR LOST DATA, REGARDLESS OF THE FORESEEABILITY OF THOSE DAMAGES) ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE SITE OR ANY OTHER MATERIALS OR SERVICES PROVIDED TO YOU BY COMPANY. IN NO EVENT WILL superjs.org BE LIABLE FOR THE RESULTS OF YOUR USE OR MISUSE OF THE INFORMATION PROVIDED BY THIS SITE, INCLUDING ANY USE CONTRARY TO UNITED STATES FEDERAL OR STATE LAW; OR FOR ANY INDIRECT, SPECIAL, OR CONSEQUENTIAL DAMAGES. This limitation shall apply regardless of whether the damages arise out of breach of contract, tort, or any other legal theory or form of action.<br><br>

AFFILIATED AND THIRD PARTY SITES. superjs.org has no control over, and no liability for any third-party websites or materials or products and services provided therein. Superjs.org works with a number of partners, affiliates, and advertisers, and content providers whose Internet sites may be linked with or incorporated into the Site. Because neither Company nor the Site has control over the content and performance of these third party sites, Company makes no guarantees about the accuracy, currency, content, or quality of the information provided by such sites, and Company assumes no responsibility for unintended, objectionable, inaccurate, misleading, or unlawful content that may reside on those sites.<br><br>

INDEMNITY. You agree to indemnify Company for certain of your acts and omissions. You agree to indemnify, defend, and hold harmless Company, its partners, affiliates, officers, directors, employees, consultants, agents, and representatives and third-party beneficiaries from any and all third party claims, losses, liability, damages, and/or costs (including reasonable attorney fees and costs) arising from your access to or use of the Site, your violation of these Terms of Use, or your infringement, or infringement by any other user of your account, of any intellectual property or other right of any person or entity. Company will notify you promptly of any such claim, loss, liability, or demand, and will provide you with reasonable assistance, at your expense, in defending any such claim, loss, liability, damage, or cost.<br><br>

COPYRIGHT; TRADEMARK. All contents of Site or Service are: Copyright © 2018, Jekyll Technologies LLC. All rights reserved.<br><br>

No material can be downloaded except as provided via the Site interface, and except for your own personal use provided you have retained any relevant copyright and other proprietary notices which may be contained in the Content. You may not reuse, distribute, modify, repost any content of this Site for public or commercial uses such as logos, text, images, without the express written permission of superjs.org.<br><br>

"superjs.org," "Jekyll Technologies LLC," as well as all logos and similar images and text found on superjs.org or any other sites controlled or operated by superjs.org, are trademarks of superjs.org.<br><br>

NO LICENSE. Nothing contained on the Site should be understood as granting you a license to use any of the trademarks, service marks, or logos owned by Company or by any third party.<br><br>

GOVERNING LAW. These Terms of Use shall be construed in accordance with and governed by the laws of the State of California, without reference to their rules regarding conflicts of law. You hereby irrevocably consent to the exclusive jurisdiction of the state or federal courts in the County of San Diego, California, USA in all disputes arising out of or related to the use of the Site or Service.<br><br>

SEVERABILITY; WAIVER. If, for whatever reason, a court of competent jurisdiction finds any term or condition in these Terms of Use to be unenforceable, all other terms and conditions will remain unaffected and in full force and effect. No waiver of any breach of any provision of these Terms of Use shall constitute a waiver of any prior, concurrent, or subsequent breach of the same or any other provisions hereof, and no waiver shall be effective unless made in writing and signed by an authorized representative of the waiving party.<br><br>

MODIFICATIONS. Superjs.org may, in its sole discretion and without prior notice, (a) revise these Terms of Use; (b) modify the Site and/or the Service; and (c) discontinue the Site and/or Service at any time. Superjs.org shall post any revision to these Terms of Use to the Site, and the revision shall be effective immediately on such posting to nonregistered Users. You agree to review these Terms of Use and other online policies posted on the Site periodically to be aware of any revisions. Superjs.org will also send registered users an email notifying them of any changes to these Terms, or otherwise advise registered users via their registration profile, and allow them an opportunity to agree to the changes, or to decline the changes and cancel the user's account. You agree that, by continuing to use or access the Site following notice of any revision, you are bound by and shall abide by any such revision.<br>
<br>
ACKNOWLEDGMENT. BY USING THE SERVICE OR ACCESSING THE SITE, YOU ACKNOWLEDGE THAT YOU HAVE READ THESE TERMS OF USE AND AGREE TO BE BOUND BY THEM.<br><br>

Amended April 1, 2018

    </div>
</template>

